blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('category/<int:pk>/',views.CategoryView.as_view(),name='category'),
    path('detail/<int:pk>/',views.DetailView.as_view(),name = 'detail'),
    path('comment/<int:post_pk>',views.CommentView.as_view(),name='comment')
]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.DetailView.as_view(),name='detail'),
    path('create/',views.CreateView.as_view(),name='create'),
    path('ajax-chat/',views.ajax_chat_add,name='ajax_chat_add'),
    path('junle/<int:pk>',views.JunleView.as_view(),name="junle"),

]

project3/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('board/',include('board.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name= models.CharField('カテゴリー名',max_length=255)
    created_at = models.DateTimeField('作成日',default=timezone.now)

    def __str__(self):
        return self.name




class Post(models.Model):

    title = models.CharField('タイトル',max_length=255)
    text = models.TextField('本文')
    created_at = models.DateTimeField('作成日',default=timezone.now)
    category = models.ForeignKey(Category,verbose_name='カテゴリ',on_delete=models.PROTECT)

    def __str__(self):
        return self.title


class Comment(models.Model):

    name = models.CharField('お名前',max_length=30,default='名無し')
    text= models.TextField('本文')
    post = models.ForeignKey(Post,verbose_name = '紐づく記事',on_delete = models.PROTECT)
    created_at = models.DateTimeField('作成日',default = timezone.now)

    def __str__(self):
        return self.text[:10]

board/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Junle(models.Model):
    name= models.CharField('ジャンル名',max_length=255)
    created_at = models.DateTimeField('作成日',default=timezone.now)

    def __str__(self):
        return self.name


class Board(models.Model):
    title = models.CharField('タイトル名',max_length=50)
    text = models.TextField('説明文')
    created_at = models.DateTimeField('作成日',default=timezone.now)
    junle = models.ForeignKey(Junle,verbose_name="ジャンル",on_delete=models.PROTECT,default=1)
    def __str__(self):
        return self.title




class Chat(models.Model):
    name = models.CharField('お名前',max_length=10,default="名無し")
    text = models.TextField('本文')
    board = models.ForeignKey(Board,verbose_name="スレッド",on_delete=models.PROTECT)
    created_at = models.DateTimeField('作成日',default=timezone.now)

    def __str__(self):
        return self.text[:10]

blog/forms.py
from django import forms
from.models import Comment

class CommentCreateForm(forms.ModelForm):

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'



    class Meta:
        model = Comment
        fields = ('name','text')

board/forms.py
from django import forms
from .models import Chat,Board

class ChatCreateForm(forms.ModelForm):

    class Meta:
        model = Chat
        fields = ('name', 'text')
        # 少しツウな書き方
        widgets = {
            'name': forms.TextInput(attrs={  # <input type="text" class="form-control"
                'class': 'form-control',
            }),
            'text': forms.Textarea(attrs={  # <textarea class="form-cotrol"
                'class': 'form-control',

            }),
        }



class BoardCreateForm(forms.ModelForm):

    class Meta:
        model = Board
        fields = ('title','text','junle')

        widgets = {
            'title': forms.TextInput(attrs={  # <input type="text" class="form-control"
                'class': 'form-control',
            }),
            'junle': forms.Select(attrs={  # <textarea class="form-cotrol"
                'class': 'form-control',
            }),
            'test': forms.Textarea(attrs={  # <textarea class="form-cotrol"
                'class': 'form-control',

            }),

        }

blog/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404,redirect
from django.views import generic
from .forms import CommentCreateForm
from .models import Post,Category,Comment


class IndexView(generic.ListView):
    model = Post
    paginate_by = 2

    def get_queryset(self):
        queryset = Post.objects.order_by('-created_at')
        keyword = self.request.GET.get('keyword')

        if keyword:
            queryset = queryset.filter(Q(title__icontains=keyword) | Q(text__icontains = keyword)
            )

        return queryset



class CategoryView(generic.ListView):
    model = Post
    paginate_by = 10


    def get_queryset(self):
        """
        category = get_object_or_404(Category,pk = self.kwargs['pk'])
        queryset = Post.objects.order_by('-created_at').filter(category=category)
        """

        category_pk = self.kwargs['pk']
        queryset = Post.objects.order_by('-created_at').filter(category__pk = category_pk)
        return queryset



class DetailView(generic.DetailView):
    model = Post




class CommentView(generic.CreateView):

    model = Comment
    form_class =CommentCreateForm

    def form_valid(self,form):

        post_pk = self.kwargs['post_pk']
        comment = form.save(commit=False)
        comment.post = get_object_or_404(Post,pk=post_pk)
        comment.save()
        return redirect('blog:detail',pk=post_pk)

board/views.py
from django.shortcuts import render
from django.db.models import Q
from django.shortcuts import get_object_or_404,redirect
from django.views.generic.edit import ModelFormMixin
from django.utils import timezone
from django.http import JsonResponse
from django.views import generic
from .models import Board,Chat
from .forms import ChatCreateForm,BoardCreateForm

# Create your views here.
class IndexView(generic.ListView):
    model = Board
    paginate_by = 3

    def get_queryset(self):
        queryset = Board.objects.order_by('-created_at')
        keyword = self.request.GET.get('keyword')

        if keyword:
            queryset = queryset.filter(Q(title__icontains=keyword) | Q(text__icontains = keyword)
            )

        return queryset

class CreateView(generic.CreateView):
    model = Board
    form_class= BoardCreateForm

    def form_valid(self,form):
        board = form
        board.save()
        return redirect('board:index')


class DetailView(ModelFormMixin,generic.DetailView):

    model = Board
    form_class =ChatCreateForm

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books

        return context


    def form_valid(self,form):

        board_pk = self.kwargs['pk']
        chat = form.save(commit=False)
        chat.board = get_object_or_404(Board,pk=board_pk)
        chat.save()
        return redirect('board:detail',pk=board_pk)



    def post(self, request, *args, **kwargs):

        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            self.object = self.get_object()
            return self.form_invalid(form)


class JunleView(generic.ListView):
    mdoel = Board
    def get_queryset(self):
        junle_pk = self.kwargs['pk']
        queryset = Board.objects.order_by('-created_at').filter(junle_id = junle_pk)
        return queryset




def ajax_chat_add(request):

    name = request.POST.get('name')
    text = request.POST.get('text')
    board_pk = int(request.POST.get('board_pk'))
    board = list(Board.objects.filter(pk=board_pk))

    chat = Chat.objects.create(name = name,text=text,board=board[0])

    d = {
        'name': chat.name,
        'text': chat.text,
        'created_at': timezone.datetime.now().strftime("%Y年%-m月%-d日 %-H:%-M")
    }
    return JsonResponse(d)

blog/templates/blog/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>ブログ</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">ブログ</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'board:index' %}">掲示板</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0"method ="GET" action="{% url 'blog:index' %}" >
          <input class="form-control mr-sm-2" type="text" name= "keyword" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="jumbotron">
      <h1 class="display-3">なんでもブログ</h1>
      <p class="lead"></p>
      <hr class="my-2">
    </div>

    <div class="container">
      <div class= "row">
        <div class="col-md-8">
          {% block content %}
          {% endblock %}
        </div>
        <div class="col-md-4 ">
          <ul class="list-group">
            <li class="list-group-item bg-dark text-white">カテゴリー覧</li>
            {% for category in category_list %}
              <li class="list-group-item"><a href="{% url 'blog:category' category.pk %}">{{category}}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>

    <footer class ="bg-dark text-white text-center py-3">
      <p>木下</p>
    </footer>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}

{% block content %}
<form action ="" method="POST">
  {{ form.non_field_errors }}
  {% for field in form %}
  <div class="form-group">
    <label for ="{{ field.id_for_label }}">{{ field.label_tag }}</label>
    {{field}}
    {{field.errors}}
  </div>
  {%endfor%}
  {%csrf_token%}
  <button type="submit" class= "btn btn-dark">送信</button>
</form>



{% endblock %}

blog/templates/blog/page.html
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="card mb-3">
  <h2 class="card-header bg-dark text-white">{{post.title}}</h2>
  <div class="card-body">
    <p>{{ post.created_at}},{{ post.category }}</p>
    {{post.text| linebreaksbr}}
  </div>
</div>
<a class ="btn btn-dark" href ="{% url 'blog:comment' post.pk %}">コメント投稿ページへ</a>

<h4>コメント一覧</h4>
{% for comment in post.comment_set.all %}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">お名前：{{ comment.name }}</h5>
    <p class="card-text">
     {{comment.text|linebreaksbr}}
    </p>
  </div>
</div>


{% endfor %}


{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}

{% for post in post_list %}
  <div class="card mb-3">
    <h2 class="card-header bg-dark text-white">{{post.title}}</h2>
    <div class="card-body">
      <p>{{ post.created_at}},{{ post.category }}</p>
      <a href="{%url 'blog:detail' post.pk%}" class="btn btn-dark">続きを読む</a>
    </div>
  </div>
{% endfor %}

{% include 'blog/page.html' %}

{% endblock %}

board/templates/board/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>掲示板</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">掲示板</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:index' %}">ブログ <span class="sr-only">(current)</span></a>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'board:index' %}">掲示板</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0"method ="GET" action="{% url 'board:index' %}" >
          <input class="form-control mr-sm-2" type="text" name= "keyword" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="jumbotron">
      <h1 class="display-3">掲示板</h1>
      <p class="lead">自由に書き込みできる掲示板です</p>
      <hr class="my-2">
      <a href="{% url 'board:create' %}" class="btn btn-dark" >掲示板作成</a>
    </div>
    </div>

    <div class="container">
      <div class= "row">
        <div class="col-md-8">
          {% block content %}
          {% endblock %}
        </div>
        <div class="col-md-4 ">
          <ul class="list-group">
            <li class="list-group-item bg-dark text-white">ジャンルー覧</li>
            {% for junle in junle_list %}
              <li class="list-group-item"><a href="{%url 'board:junle' junle.pk%}">{{junle}}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>

    <footer class ="bg-dark text-white text-center py-3">
      <p>木下</p>
    </footer>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock %}
  </body>
</html>

board/templates/board/board_detail.html
{% extends 'board/base.html'%}


{% block content %}
<div class="card mb-3" board-id="{{board.pk}}">
  <h2 class="card-header bg-dark text-white">{{board.title}}</h2>
  <div class="card-body">
    <p>{{ board.created_at}},{{ board.junle }}</p>
    {{board.text| linebreaksbr}}
  </div>

</div>
{% for chat in board.chat_set.all %}
<div class="card">
  <div class="card-body">
    <p>{{chat.name}}  {{chat.created_at}}</p>
    <p>{{chat.text}}</p>
  </div>
</div>
{%endfor%}

<form action ="" id="ajax-add-post" method="POST">
  {{ form.non_field_errors }}
  {% for field in form %}
  <div class="form-group">
    <label for ="{{ field.id_for_label }}">{{ field.label_tag }}</label>
    {{field}}
    {{field.errors}}
  </div>
  {%endfor%}
  {%csrf_token%}
  <input type="submit"  class= "btn btn-dark" value ="書き込み"></input>
</form>

{% endblock %}
{% block extrajs %}
    <script>
    $(function(){
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });








        function buildHTML(chat){

          var html = `
                    <div class="card">
                      <div class="card-body">
                        <p>${ chat.name }  ${chat.created_at}</p>
                        <p>${chat.text}</p>
                      </div>
                    </div>`


          return html
        }

        $('#ajax-add-post').on('submit', function (e) {
            console.log('test')
            e.preventDefault();

            $.ajax({
                'url': '{% url "board:ajax_chat_add" %}',
                'type': 'POST',
                'data': {
                    'name': $('#id_name').val(),
                    'text': $('#id_text').val(),
                    'board_pk': $('.mb-3').attr('board-id')
                },
                'dataType': 'json'
            })
            .done(function(data){
              var html = buildHTML(data);
              $('.card').last().after(html)
              $('#id_text').val('')

            })
            .fail(function(){
              alert('error');
            })
        });

    });
    </script>

{% endblock %}

board/templates/board/board_form.html
{% extends 'board/base.html' %}

{% block content %}
<form action ="" method="POST">
  {{ form.non_field_errors }}
  {% for field in form %}
  <div class="form-group">
    <label for ="{{ field.id_for_label }}">{{ field.label_tag }}</label>
    {{field}}
    {{field.errors}}
  </div>
  {%endfor%}
  {%csrf_token%}
  <button type="submit" class= "btn btn-dark">送信</button>
</form>



{% endblock %}

board/templates/board/board_list.html
{% extends 'board/base.html' %}

{% block content %}

{% for board in board_list %}
  <div class="card mb-3">
    <h2 class="card-header bg-dark text-white">{{board.title}}</h2>
    <div class="card-body">
      <h3 class="badge badge-secondary"><span>{{board.junle}}</span></h3>
      <h5>{{board.text}} </h5>
      <a href="{% url 'board:detail' board.pk %}" class="btn btn-dark">書き込み</a>
    </div>
  </div>
{% endfor %}



{% endblock %}